"""
File Generator Module
Generate files and folders dengan content berdasarkan instruksi user
Mirip dengan Gemini's file generation capability
"""

import os
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime
import re

logger = logging.getLogger(__name__)


class FileGenerator:
    """Generate files and folders with content based on instructions"""
    
    # Code templates untuk berbagai tipe file
    TEMPLATES = {
        'python': {
            'hello_world': '''#!/usr/bin/env python3
"""
{description}
Generated by Irma on {timestamp}
"""

def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
''',
            'class': '''#!/usr/bin/env python3
"""
{description}
"""

class {class_name}:
    """Class description"""
    
    def __init__(self):
        pass
    
    def method_example(self):
        """Method example"""
        pass
''',
            'flask_app': '''#!/usr/bin/env python3
"""
{description}
Flask application generated by Irma
"""

from flask import Flask, render_template, jsonify

app = Flask(__name__)

@app.route('/')
def index():
    return "Hello from Flask!"

@app.route('/api/data')
def get_data():
    return jsonify({{
        'status': 'success',
        'message': 'API is working'
    }})

if __name__ == '__main__':
    app.run(debug=True)
''',
        },
        'html': {
            'basic': '''<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p>{description}</p>
    
    <script>
        console.log('Generated by Irma on {timestamp}');
    </script>
</body>
</html>
''',
            'tailwind': '''<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto px-4 py-8">
        <div class="bg-white rounded-lg shadow-lg p-6">
            <h1 class="text-3xl font-bold mb-4">{title}</h1>
            <p class="text-gray-700">{description}</p>
        </div>
    </div>
</body>
</html>
''',
        },
        'javascript': {
            'basic': '''/**
 * {description}
 * Generated by Irma on {timestamp}
 */

function main() {{
    console.log('Hello, World!');
}}

main();
''',
            'class': '''/**
 * {description}
 */

class {class_name} {{
    constructor() {{
        // Constructor
    }}
    
    exampleMethod() {{
        // Method implementation
    }}
}}

// Export
export default {class_name};
''',
        },
        'css': {
            'basic': '''/**
 * {description}
 * Generated by Irma on {timestamp}
 */

:root {{
    --primary-color: #8B5CF6;
    --secondary-color: #EC4899;
}}

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    line-height: 1.6;
    color: #333;
}}

.container {{
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}}
''',
        },
        'json': {
            'config': {{
                "name": "{name}",
                "version": "1.0.0",
                "description": "{description}",
                "generated_by": "Irma",
                "timestamp": "{timestamp}"
            }},
            'data': {{
                "data": [],
                "meta": {{
                    "generated_by": "Irma",
                    "timestamp": "{timestamp}"
                }}
            }},
        },
        'markdown': {
            'readme': '''# {title}

{description}

## Features

- Feature 1
- Feature 2
- Feature 3

## Installation

```bash
# Installation instructions here
```

## Usage

```python
# Usage example here
```

## License

MIT

---

*Generated by Irma on {timestamp}*
''',
            'documentation': '''# {title}

## Overview

{description}

## Table of Contents

1. [Introduction](#introduction)
2. [Getting Started](#getting-started)
3. [API Reference](#api-reference)

## Introduction

Introduction text here.

## Getting Started

Getting started guide here.

## API Reference

API documentation here.

---

*Last updated: {timestamp}*
''',
        },
    }
    
    def __init__(self, file_validator, audit_logger, base_dir: str = None):
        """
        Args:
            file_validator: FileAccessValidator instance
            audit_logger: AuditLogger instance
            base_dir: Base directory untuk generate files (default: Downloads)
        """
        self.validator = file_validator
        self.audit_logger = audit_logger
        self.base_dir = base_dir or os.path.expanduser("~\\Downloads\\IrmaGenerated")
        
        # Create base directory if not exists
        os.makedirs(self.base_dir, exist_ok=True)
        
        logger.info(f"File generator initialized: {self.base_dir}")
    
    def generate_file(self, instruction: str, file_type: str = 'txt', 
                     file_name: str = None, content: str = None) -> Dict:
        """
        Generate file based on instruction
        
        Args:
            instruction: User instruction
            file_type: File type (py, html, js, css, json, md, txt)
            file_name: Optional file name
            content: Optional explicit content
            
        Returns:
            Dict dengan status dan file path
        """
        try:
            # Parse instruction untuk extract details
            details = self._parse_instruction(instruction, file_type)
            
            # Generate file name jika belum ada
            if not file_name:
                file_name = details.get('name', f"generated_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
            
            # Ensure extension
            if not file_name.endswith(f".{file_type}"):
                file_name = f"{file_name}.{file_type}"
            
            # Generate content jika belum ada
            if not content:
                content = self._generate_content(file_type, details, instruction)
            
            # Create file path
            file_path = os.path.join(self.base_dir, file_name)
            
            # Validate path
            if not self.validator.validate_path(file_path):
                raise PermissionError(f"Path not allowed: {file_path}")
            
            # Write file
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            # Log
            self.audit_logger.log_action(
                action="file_generate",
                resource=file_path,
                status="success"
            )
            
            logger.info(f"File generated: {file_path}")
            
            return {
                'success': True,
                'file_path': file_path,
                'file_name': file_name,
                'file_type': file_type,
                'size': len(content)
            }
            
        except Exception as e:
            logger.error(f"Error generating file: {e}")
            self.audit_logger.log_action(
                action="file_generate",
                resource=file_name or "unknown",
                status="error",
                details=str(e)
            )
            return {
                'success': False,
                'error': str(e)
            }
    
    def generate_project(self, project_name: str, project_type: str = 'basic',
                        description: str = "") -> Dict:
        """
        Generate entire project structure
        
        Args:
            project_name: Project name
            project_type: Project type (basic, flask, react, etc)
            description: Project description
            
        Returns:
            Dict dengan status dan created files
        """
        try:
            project_path = os.path.join(self.base_dir, project_name)
            os.makedirs(project_path, exist_ok=True)
            
            created_files = []
            
            if project_type == 'flask':
                # Flask project structure
                structure = {
                    'app.py': self._get_template('python', 'flask_app'),
                    'requirements.txt': 'flask==3.0.0\nflask-cors==4.0.0\n',
                    'README.md': self._get_template('markdown', 'readme'),
                    'templates/index.html': self._get_template('html', 'basic'),
                    'static/style.css': self._get_template('css', 'basic'),
                }
                
                for file_path, template in structure.items():
                    full_path = os.path.join(project_path, file_path)
                    os.makedirs(os.path.dirname(full_path), exist_ok=True)
                    
                    content = template.format(
                        title=project_name,
                        description=description or f"{project_name} Flask Application",
                        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                        name=project_name
                    )
                    
                    with open(full_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    
                    created_files.append(file_path)
            
            elif project_type == 'basic':
                # Basic project structure
                structure = {
                    'main.py': self._get_template('python', 'hello_world'),
                    'README.md': self._get_template('markdown', 'readme'),
                    'config.json': json.dumps(self.TEMPLATES['json']['config'], indent=2),
                }
                
                for file_path, template in structure.items():
                    full_path = os.path.join(project_path, file_path)
                    
                    if file_path.endswith('.json'):
                        content = template
                    else:
                        content = template.format(
                            title=project_name,
                            description=description or f"{project_name} Project",
                            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                            name=project_name
                        )
                    
                    with open(full_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    
                    created_files.append(file_path)
            
            self.audit_logger.log_action(
                action="project_generate",
                resource=project_path,
                status="success",
                details=f"Created {len(created_files)} files"
            )
            
            return {
                'success': True,
                'project_path': project_path,
                'project_name': project_name,
                'created_files': created_files,
                'file_count': len(created_files)
            }
            
        except Exception as e:
            logger.error(f"Error generating project: {e}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def _parse_instruction(self, instruction: str, file_type: str) -> Dict:
        """Parse instruction untuk extract details"""
        details = {
            'description': instruction,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        }
        
        # Extract name jika ada
        name_match = re.search(r'nama[\\s]*["\']?([a-zA-Z0-9_\\-]+)["\']?', instruction, re.IGNORECASE)
        if name_match:
            details['name'] = name_match.group(1)
        
        # Extract class name untuk Python/JavaScript
        if file_type in ['py', 'js']:
            class_match = re.search(r'class[\\s]+([A-Z][a-zA-Z0-9_]*)', instruction)
            if class_match:
                details['class_name'] = class_match.group(1)
            else:
                details['class_name'] = 'MyClass'
        
        # Extract title untuk HTML/Markdown
        if file_type in ['html', 'md']:
            details['title'] = details.get('name', 'Untitled')
        
        return details
    
    def _generate_content(self, file_type: str, details: Dict, instruction: str) -> str:
        """Generate content based on file type"""
        
        # Determine template type
        template_type = 'basic'
        if 'class' in instruction.lower():
            template_type = 'class'
        elif 'flask' in instruction.lower():
            template_type = 'flask_app'
        elif 'tailwind' in instruction.lower():
            template_type = 'tailwind'
        elif 'readme' in instruction.lower():
            template_type = 'readme'
        
        # Get template
        template = self._get_template(file_type, template_type)
        
        # Format template
        try:
            content = template.format(**details)
        except KeyError:
            # Jika ada missing keys, gunakan safe defaults
            safe_details = {
                'description': details.get('description', 'Generated by Irma'),
                'timestamp': details.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
                'title': details.get('title', 'Untitled'),
                'name': details.get('name', 'generated'),
                'class_name': details.get('class_name', 'MyClass'),
            }
            content = template.format(**safe_details)
        
        return content
    
    def _get_template(self, file_type: str, template_type: str) -> str:
        """Get template by type"""
        templates_map = {
            'py': 'python',
            'js': 'javascript',
            'md': 'markdown',
        }
        
        file_type_key = templates_map.get(file_type, file_type)
        
        if file_type_key in self.TEMPLATES:
            if template_type in self.TEMPLATES[file_type_key]:
                template = self.TEMPLATES[file_type_key][template_type]
                
                # Special handling untuk JSON
                if isinstance(template, dict):
                    return json.dumps(template, indent=2)
                
                return template
        
        # Fallback ke basic template
        return f'''# Generated File

Generated by Irma on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

No template available for this file type.
'''


# Export
__all__ = ['FileGenerator']
